name: orgalive
description: Orgalive - Seu aplicativo de gestão financeira

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_performance: ^0.8.0+4
  font_awesome_flutter: ^9.2.0
  firebase_crashlytics: ^2.4.5
  flutter_masked_text2: ^0.9.1
  firebase_analytics: ^8.3.4
  firebase_storage: ^10.2.5
  connectivity_plus: ^2.2.0
  calendar_timeline: ^1.0.4
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.4
  google_sign_in: ^5.2.3
  awesome_select: ^5.1.0
  google_nav_bar: ^5.0.5
  firebase_core: ^1.11.0
  image_picker: ^0.8.4+4
  firebase_auth: ^3.3.5
  find_dropdown: ^1.0.0
  graphic: ^0.8.0
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
