name: orgalive
description: Orgalive - Seu aplicativo de gestão financeira

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_performance: ^0.8.0+8
  font_awesome_flutter: ^10.1.0
  firebase_crashlytics: ^2.6.1
  flutter_masked_text2: ^0.9.1
  firebase_analytics: ^9.1.3
  firebase_storage: ^10.2.10
  connectivity_plus: ^2.2.1
  calendar_timeline: ^1.0.4
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.4
  google_sign_in: ^5.2.4
  google_nav_bar: ^5.0.6
  firebase_core: ^1.14.0
  image_picker: ^0.8.4+11
  firebase_auth: ^3.3.12
  find_dropdown: ^1.0.0
  flutter_mobx: ^2.0.4
  provider: ^6.0.2
  graphic: ^0.9.1
  mobx: ^2.0.6+1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.1
  mobx_codegen: ^2.0.5+2
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8

  # configuracao da splash
flutter_native_splash:
  color: "#363435"
  image: assets/img/logo2.png
  android: true
  ios: true
  fullscreen: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
